<template>
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Simulasi Penilaian</h1>
          </div>
          <!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item">
                <a href="#">Home</a>
              </li>
              <li class="breadcrumb-item active">Simulasi</li>
            </ol>
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-6 offset-md-3">
            <div class="row">
              <div class="col-3">
                <i class="fas fa-circle text-success" style="margin-right : 5px"></i>
                <p class="text" style="display:inline-block">Score = 4.0</p>
              </div>
              <div class="col-3">
                <i class="fas fa-circle text-info" style="margin-right : 5px"></i>
                <p class="text" style="display:inline-block">Score = 3.0 - 3.99</p>
              </div>
              <div class="col-3">
                <i class="fas fa-circle text-warning" style="margin-right : 5px"></i>
                <p class="text" style="display:inline-block">Score = 2.0 - 2.99</p>
              </div>
              <div class="col-3">
                <i class="fas fa-circle text-danger" style="margin-right : 5px"></i>
                <p class="text" style="display:inline-block">Score = 0 - 1.99</p>
              </div>
            </div>
          </div>
        </div>
        
        
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">3.1.1</h3>

            <div class="card-tools">
              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-widget="collapse">
                  <i class="fas fa-minus"></i>
                </button>
              </div>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <div class="row">
              <div class="col-md-3 col-sm-6 col-12">
                <div class="info-box bg-success">
                  <span class="info-box-icon">
                    <i class="fas fa-thumbs-up"></i>
                  </span>

                  <div class="info-box-content">
                    <span class="info-box-text">Rasio Ikut Seleksi : Daya Tampung</span>
                    <span class="info-box-number">5.43</span>

                    <div class="progress">
                      <div class="progress-bar" style="width: 100%"></div>
                    </div>
                    <span class="progress-description">Score = 4</span>
                    <div class="dropdown">
                      <a data-toggle="dropdown" aria-expanded="true" style="float: right; color:white" href="#" class="dropdown-toggle">
                        <i class="fas fa-info-circle"></i>
                      </a>
                      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" x-placement="bottom-end">
                        <span class="dropdown-header">15 Notifications</span>
                        <a href="#" class="dropdown-item">
                          <i class="fas fa-file mr-2"></i> 3 new reports
                          <span class="float-right text-muted text-sm">2 days</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                      </div>
                    </div>
                  </div>
                  <!-- /.info-box-content -->
                </div>
                <!-- /.info-box -->
              </div>
              <div class="col-md-3 col-sm-6 col-12">
                <div class="info-box bg-info">
                  <span class="info-box-icon">
                    <i class="fas fa-thumbs-up"></i>
                  </span>

                  <div class="info-box-content">
                    <span class="info-box-text">Rasio Registrasi : Lulus seleksi</span>
                    <span class="info-box-number">91%</span>

                    <div class="progress">
                      <div class="progress-bar" style="width: 100%"></div>
                    </div>
                    <span class="progress-description">Score = 3.60</span>
                    <div class="dropdown">
                      <a data-toggle="dropdown" aria-expanded="true" style="float: right; color:white" href="#" class="dropdown-toggle">
                        <i class="fas fa-info-circle"></i>
                      </a>
                      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" x-placement="bottom-end">
                        <span class="dropdown-header">15 Notifications</span>
                        <a href="#" class="dropdown-item">
                          <i class="fas fa-file mr-2"></i> 3 new reports
                          <span class="float-right text-muted text-sm">2 days</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                      </div>
                    </div>
                  </div>
                  <!-- /.info-box-content -->
                </div>
                <!-- /.info-box -->
              </div>
              <div class="col-md-3 col-sm-6 col-12">
                <div class="info-box bg-success">
                  <span class="info-box-icon">
                    <i class="fas fa-thumbs-up"></i>
                  </span>

                  <div class="info-box-content">
                    <span class="info-box-text">Rasio Mahasiswa Transfer : Tidak</span>
                    <span class="info-box-number">0</span>

                    <div class="progress">
                      <div class="progress-bar" style="width: 100%"></div>
                    </div>
                    <span class="progress-description">Score = 4</span>
                    <div class="dropdown">
                      <a data-toggle="dropdown" aria-expanded="true" style="float: right; color:white" href="#" class="dropdown-toggle">
                        <i class="fas fa-info-circle"></i>
                      </a>
                      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" x-placement="bottom-end">
                        <span class="dropdown-header">15 Notifications</span>
                        <a href="#" class="dropdown-item">
                          <i class="fas fa-file mr-2"></i> 3 new reports
                          <span class="float-right text-muted text-sm">2 days</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                      </div>
                    </div>
                  </div>
                  <!-- /.info-box-content -->
                </div>
                <!-- /.info-box -->
              </div>
              <div class="col-md-3 col-sm-6 col-12">
                <div class="info-box bg-warning">
                  <span class="info-box-icon">
                    <i class="fas fa-minus"></i>
                  </span>

                  <div class="info-box-content">
                    <span class="info-box-text">Rata-rata indeks IPK 5 Tahun</span>
                    <span class="info-box-number">2.5</span>

                    <div class="progress">
                      <div class="progress-bar" style="width: 100%"></div>
                    </div>
                    <span class="progress-description">Score = 2.60</span>
                    <div class="dropdown">
                      <a data-toggle="dropdown" aria-expanded="true" style="float: right; color:white" href="#" class="dropdown-toggle">
                        <i class="fas fa-info-circle"></i>
                      </a>
                      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" x-placement="bottom-end">
                        <span class="dropdown-header">15 Notifications</span>
                        <a href="#" class="dropdown-item">
                          <i class="fas fa-file mr-2"></i> 3 new reports
                          <span class="float-right text-muted text-sm">2 days</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                      </div>
                    </div>
                  </div>
                  <!-- /.info-box-content -->
                </div>
                <!-- /.info-box -->
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-6">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">3.1.2</h3>

                <div class="card-tools">
                  <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-widget="collapse">
                      <i class="fas fa-minus"></i>
                    </button>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <div class="row">
                  <div class="col-12">
                    <div class="info-box bg-danger">
                      <span class="info-box-icon">
                        <i class="fas fa-thumbs-down"></i>
                      </span>

                      <div class="info-box-content">
                        <span class="info-box-text">Beban SKS Dosen</span>
                        <span class="info-box-number">19</span>

                        <div class="progress">
                          <div class="progress-bar" style="width: 10%"></div>
                        </div>
                        <span class="progress-description">Score = 1</span>
                      </div>
                      <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-6">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">3.1.3</h3>

                <div class="card-tools">
                  <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-widget="collapse">
                      <i class="fas fa-minus"></i>
                    </button>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <div class="row">
                  <!-- <table class="table table-bordered table-striped">
                  <tbody>
                    <tr>
                      <td>Internasional :</td>
                      <td>20</td>
                    </tr>
                    <tr>
                      <td>Nasional :</td>
                      <td>40</td>
                    </tr>
                    <tr>
                      <td>Daerah :</td>
                      <td>12</td>
                    </tr>
                    <tr>
                      <td>Lokal :</td>
                      <td>50</td>
                    </tr>
                  </tbody>
                  </table>-->
                  <div class="col">
                    <div class="info-box bg-success">
                      <span class="info-box-icon">
                        <i class="fas fa-thumbs-up"></i>
                      </span>

                      <div class="info-box-content">
                        <span class="info-box-text">Prestasi dan Reputasi</span>
                        <span class="info-box-number">>= Internasional</span>

                        <div class="progress">
                          <div class="progress-bar" style="width: 90%"></div>
                        </div>
                        <span class="progress-description">Score = 4</span>
                      </div>
                      <!-- /.info-box-content -->
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="card">
          <div class="card-header">
            <h3 class="card-title">3.1.4</h3>

            <div class="card-tools">
              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-widget="collapse">
                  <i class="fas fa-minus"></i>
                </button>
              </div>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <div class="row">
              <div class="col-6">
                <div class="info-box bg-warning">
                  <span class="info-box-icon">
                    <i class="fas fa-minus"></i>
                  </span>

                  <div class="info-box-content">
                    <span class="info-box-text">Kelulusan Tepat Waktu</span>
                    <span class="info-box-number">40%</span>

                    <div class="progress">
                      <div class="progress-bar" style="width: 40%"></div>
                    </div>
                    <span class="progress-description">Score = 3.50</span>
                  </div>
                  <!-- /.info-box-content -->
                </div>
              </div>
              <div class="col-6">
                <div class="info-box bg-success">
                  <span class="info-box-icon">
                    <i class="fas fa-thumbs-up"></i>
                  </span>

                  <div class="info-box-content">
                    <span class="info-box-text">Mahasiswa DO</span>
                    <span class="info-box-number">4.2%</span>

                    <div class="progress">
                      <div class="progress-bar" style="width: 90%"></div>
                    </div>
                    <span class="progress-description">Score = 4</span>
                  </div>
                  <!-- /.info-box-content -->
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">3.2</h3>

            <div class="card-tools">
              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-widget="collapse">
                  <i class="fas fa-minus"></i>
                </button>
              </div>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <div class="row"></div>
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">3.3.1</h3>

            <div class="card-tools">
              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-widget="collapse">
                  <i class="fas fa-minus"></i>
                </button>
              </div>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <div class="row"></div>
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">3.3.2</h3>

            <div class="card-tools">
              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-widget="collapse">
                  <i class="fas fa-minus"></i>
                </button>
              </div>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <div class="row"></div>
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">3.3.3</h3>

            <div class="card-tools">
              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-widget="collapse">
                  <i class="fas fa-minus"></i>
                </button>
              </div>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <div class="row"></div>
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">3.4</h3>

            <div class="card-tools">
              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-widget="collapse">
                  <i class="fas fa-minus"></i>
                </button>
              </div>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <div class="row"></div>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
</template>

<script>
export default {
  mounted() {
    console.log("Component mounted.");
  }
};
</script>