<template>
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Standar 3.3</h1>
                    </div>
                    <!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Standar 3.3</li>
                        </ol>
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">

                <div class="row">
          <div class="col-6">
            <div class="info-box">
              <span class="info-box-icon bg-info"><i class="fas fa-clock"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Waktu Tunggu Lulusan</span>
                <span class="info-box-number">3 Minggu</span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->
          <div class="col-6">
            <div class="info-box">
              <span class="info-box-icon bg-success"><i class="fas fa-percent"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Presentase Keseuaian Bidang</span>
                <span class="info-box-number">80%</span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->

                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Evaluasi Lulusan</h3>
                    </div>
                    <div class="card-body">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th rowspan="3">No</th>
                                <th rowspan="3">Jenis Kemampuan </th>
                                <th colspan="4">Tanggapan Pihak Pengguna</th>
                                <th rowspan="3">Rencana Tindak Lanjut oleh Program
                                    <br>Studi</th>
                            </tr>
                            <tr>
                                <th>Sangat Baik</th>
                                <th>Baik</th>
                                <th>Cukup</th>
                                <th>Kurang</th>
                            </tr>
                            <tr>
                                <th>%</th>
                                <th>%</th>
                                <th>%</th>
                                <th>%</th>
                            </tr>
                            
                            <tr>
                                <th>(1)</th>
                                <th>(2)</th>
                                <th>(3)</th>
                                <th>(4)</th>
                                <th>(5)</th>
                                <th>(6)</th>
                                <th>(7)</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>1</td>
                                <td>Intergritas (etika dan moral)</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>Keahlian berdasarkan bidang
                                    <br>ilmu (profresionalisme)</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>3</td>
                                <td>Bahasa Inggris</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>4</td>
                                <td>Penggunaan Teknologi
                                    <br>Informasi</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>5</td>
                                <td>Komunikasi</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>6</td>
                                <td>Kerjasama tim</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>7</td>
                                <td>Pengembangan diri</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td colspan="2">Total</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

<div class="row">
    <div class="col-4">
               <div class="card">
              <div class="card-header">
                <h3 class="card-title">Data Pendukung</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0" style="height: 300px;">
                <table class="table table-head-fixed text-center">
                  <thead>
                    <tr>
                      <th>No</th>
                      <th>Nama Data</th>
                      <th>Lihat</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>1</td>
                      <td>Data Tracer Study</td>
                      <td><i class="fas fa-eye table-icon indigo"></i></td>
                    </tr>
                    <tr>
                      <td>2</td>
                      <td>Pendapat Pengguna Lulusan</td>
                      <td><i class="fas fa-eye table-icon indigo"></i></td>
                    </tr>
                    <tr>
                      <td>3</td>
                      <td>Profil Masa Tunggu</td>
                      <td><i class="fas fa-eye table-icon indigo"></i></td>
                    </tr>
                    <tr>
                      <td>4</td>
                      <td>Profil Kesesuaian Bidang</td>
                      <td><i class="fas fa-eye table-icon indigo"></i></td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
                <div class="card-footer text-right">
                  <button type="button" class="btn btn-primary">Download All</button>
                </div>
            </div>
            </div>
            <div class="col-5">
               <div class="card">
              <div class="card-header">
                <h3 class="card-title">Daftar Lampiran</h3>

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                    <div class="input-group-append">
                      <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0" style="height: 300px;">
                <table class="table table-head-fixed text-center">
                  <thead>
                    <tr>
                      <th>No</th>
                      <th>Nama Lampiran</th>
                      <th>Dibuat pada</th>
                      <th>Download</th>
                      <th>Operasi</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>1</td>
                      <td>Penggunan Hasil Pelacakan</td>
                      <td>11-7-2014</td>
                      <td><i class="fas fa-file-pdf table-icon red"></i></td>
                      <td><button class="btn btn-sm btn-danger">x</button></td>
                    </tr>
                    <tr>
                      <td>2</td>
                      <td>Proses Pembelajaran</td>
                      <td>11-7-2014</td>
                      <td><i class="fas fa-file-pdf table-icon red"></i></td>
                      <td><button class="btn btn-sm btn-danger">x</button></td>
                    </tr>
                    <tr>
                      <td>3</td>
                      <td>Penggalangan dana</td>
                      <td>11-7-2014</td>
                      <td><i class="fas fa-file-pdf table-icon red"></i></td>
                      <td><button class="btn btn-sm btn-danger">x</button></td>
                    </tr>
                    <tr>
                      <td>4</td>
                      <td>Bangun Jejaring</td>
                      <td>11-7-2014</td>
                      <td><i class="fas fa-file-pdf table-icon red"></i></td>
                      <td><button class="btn btn-sm btn-danger">x</button></td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
                <div class="card-footer text-right">
                  <button type="button" class="btn btn-primary">Download All</button>
                </div>
            </div>
            </div>
            

            <div class="col-3">
              <div class="card">
              <div class="card-header">
                <h3 class="card-title">Tambah Lampiran</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form">
                <div class="card-body">
                  <div class="form-group">
                    <label for="namaLampiran">Nama Lampiran</label>
                    <input type="email" class="form-control" id="namaLampiran" placeholder="Enter lampiran">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputFile">File input</label>
                    <div class="input-group">
                      <div class="custom-file">
                        <input type="file" class="custom-file-input" id="exampleInputFile">
                        <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                      </div>
                      <div class="input-group-append">
                        <span class="input-group-text" id="">Upload</span>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer text-right">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>

          </div>
                

            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
</template>

<script>
    export default {
        mounted() {
            console.log('Component mounted.')
        }
    }
</script>